server:
    port: 8080
spring:
    application:
        name: api-gateway
zuul:
    routes:
        auth-center:
            path: '/login/**'
            url: 'http://localhost:8081/'
            sensitiveHeaders: 'Cookie,Set-Cookie'
            stripPrefix: false
        services:
            path: '/api/**'
            url: 'http://localhost:8082/'

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true

demo.security.jwt.secret: secretkey